Models/ErrorViewModel.cs
namespace ProjetoMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Filme.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjetoMVC.Models
{
    [Table("filmes")]
    public class Filme
    {
        public Filme(int id, string titulo, string sinopse, string genero, string classificacao, DateTime data_lancamento)
        {
            Id = id;
            Titulo = titulo;
            Sinopse = sinopse;
            Genero = genero;
            Classificacao = classificacao;
            Data_lancamento = data_lancamento;
        }

        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Sinopse { get; set; }
        public string Genero { get; set; }
        public string Classificacao { get; set; }
        [DataType(DataType.Date)]
        public DateTime Data_lancamento { get; set; }

    }
}

Models/FilmeRepository.cs
using Npgsql;
using System.Linq.Expressions;

namespace ProjetoMVC.Models
{
    public class FilmeRepository
    {
        private readonly IConfiguration _configuration;
        private readonly string connectionString;

        public FilmeRepository(IConfiguration configuration)
        {
            _configuration = configuration;
            connectionString = _configuration.GetConnectionString("DefaultConnection");
        }

        public IEnumerable<Filme> GetAll()
        {

            var filmes = new List<Filme>();
            using (var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                var query = "SELECT * FROM filmes";
                using NpgsqlCommand command = new(query, connection);
                using NpgsqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    filmes.Add(new Filme
                    {
                        Id = Convert.ToInt32(reader["Id"]),
                        Titulo = reader["Titulo"].ToString(),
                        Sinopse = reader["Sinopse"].ToString(),
                        Genero = reader["Genero"].ToString(),
                        Classificacao = reader["Classificacao"].ToString(),
                        Data_lancamento = Convert.ToDateTime(
                            reader["Data_lancamento"])
                    });
                }
            }

            return filmes;
        }

        public void Add(Filme filme)
        {
            using (var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                var query = "INSERT INTO filmes (titulo, sinopse, genero, classificacao, data_lancamento) " +
                    "VALUES (@Titulo, @Sinopse, @Genero, @Classificacao, @Data_lancamento)";
                using var command = new NpgsqlCommand(query, connection);
                command.Parameters.AddWithValue("Titulo", filme.Titulo);
                command.Parameters.AddWithValue("Sinopse", filme.Sinopse);
                command.Parameters.AddWithValue("Genero", filme.Genero);
                command.Parameters.AddWithValue("Classificacao", filme.Classificacao);
                command.Parameters.AddWithValue("Data_lancamento", filme.Data_lancamento);

                command.ExecuteNonQuery();
            }
        }
    
        public Filme GetById(int id)
        {
            var filme = new Filme();
            using(var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                var query = "SELECT * FROM Filmes WHERE id = @id";
                using var command = new NpgsqlCommand(query, connection);
                command.Parameters.AddWithValue("id", id);
                using NpgsqlDataReader reader = command.ExecuteReader();
                
                    filme.Id = Convert.ToInt32(reader["Id"]);
                    filme.Titulo = reader["Titulo"].ToString();
                    filme.Sinopse = reader["Sinopse"].ToString();
                    filme.Genero = reader["Genero"].ToString();
                    filme.Classificacao = reader["Classificacao"].ToString();
                    filme.Data_lancamento = Convert.ToDateTime(
                        reader["Data_lancamento"]);
            }
            return filme;
        }

        public void Update(Filme filme)
        {
            var resultado = GetById(filme.Id);
            using (var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                var query = "UPDATE filmes " +
                    "SET titulo = @Titulo, sinopse = @Sinopse, genero = @Genero, " +
                    "classificacao = @Classificacao, " +
                    "data_lancamento = @Data_lancamento " +
                    "WHERE id = @id";
                using var command = new NpgsqlCommand(query, connection);
                command.Parameters.AddWithValue("Titulo", resultado.Titulo);
                command.Parameters.AddWithValue("Sinopse", resultado.Sinopse);
                command.Parameters.AddWithValue("Genero", resultado.Genero);
                command.Parameters.AddWithValue("Classificacao", resultado.Classificacao);
                command.Parameters.AddWithValue(
                    "Data_lancamento", resultado.Data_lancamento);
                command.Parameters.AddWithValue("id", filme.Id);

                command.ExecuteNonQuery();
            }
        }

        public void Delete(int id)
        {
            using (var connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                var query = "DELETE FROM filmes WHERE id = @id";
                using var command = new NpgsqlCommand(query, connection);
                command.Parameters.AddWithValue("id", id);

                command.ExecuteNonQuery();
            }
        }
    }
}

Models/IFilmeRepository.cs
namespace ProjetoMVC.Models
{
    public interface IFilmeRepository
    {
        public IEnumerable<Filme> GetAll();
        public Filme GetById(int id);
        public void AddFilme(Filme filme);
        public void UpdateFilme(Filme filme);
        public void DeleteFilme(int id);
    }
}

Controllers/FilmeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoMVC.Models;

namespace ProjetoMVC.Controllers
{
    public class FilmeController : Controller
    {
        private readonly IFilmeRepository _repository;

        public FilmeController(IFilmeRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var filmes = _repository.GetAll();
            return View(filmes);
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult AddFilme(Filme filme)
        {
            _repository.AddFilme(filme);
            return RedirectToAction("Index");
        }

        public IActionResult Detalhes(int id)
        {
            var filme = _repository.GetById(id);
            return View(filme);
        }
        
        public IActionResult UpdateFilme(Filme filme)
        {
            _repository.UpdateFilme(filme);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteFilme(int id)
        {
            _repository.DeleteFilme(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Filme/Cadastro.cshtml
@model IEnumerable<ProjetoMVC.Models.Filme>
@{
    ViewData["Title"] = "Cadastro de Filmes";
}

<h2>Adicionar Novo Filme</h2>

<form asp-action="AddFilme">
    <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" name="titulo"
        required>
    </div>
    <div class="form-group">
        <label for="sinopse">Sinopse:</label>
        <textarea class="form-control" id="sinopse" name="sinopse"
        required></textarea>
    </div>
    <div class="form-group">
        <label for="dataLancamento">Data de Lançamento:</label>
        <input type="date" class="form-control" id="dataLancamento" 
        name="data_lancamento" required>
    </div>
    <div class="form-group">
        <label for="genero">Genero:</label>
        <input type="text" class="form-control" id="genero" name="genero">
    </div>
    <div class="form-group">
        <label for="classificacao">Classificação:</label>
        <input type="text" class="form-control" id="classificacao" 
        name="classificacao">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>

Views/Filme/Detalhes.cshtml
@model ProjetoMVC.Models.Filme
@{
    ViewData["Title"] = "Cadastro de Filmes";
}

<h2>Adicionar Novo Filme</h2>

<form asp-action="Update">
    <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" name="titulo"
               value="@Model.Titulo" required>
    </div>
    <div class="form-group">
        <label for="sinopse">Sinopse:</label>
        <textarea class="form-control" id="sinopse" name="sinopse"
                  value="@Model.Sinopse" required></textarea>
    </div>
    <div class="form-group">
        <label for="dataLancamento">Data de Lançamento:</label>
        <input type="date" class="form-control" id="dataLancamento"
               name="data_lancamento" value="@Model.Data_lancamento" required>
    </div>
    <div class="form-group">
        <label for="genero">Genero:</label>
        <input type="text" class="form-control" id="genero" name="genero"
               value="@Model.Genero">
    </div>
    <div class="form-group">
        <label for="classificacao">Classificação:</label>
        <input type="text" class="form-control" id="classificacao"
               name="classificacao" value="@Model.Classificacao>
    </div>
    <button type="submit" class="btn btn-primary">Atualizar</button>
</form>

Views/Filme/Index.cshtml
@model IEnumerable<ProjetoMVC.Models.Filme>

@{
    ViewData["Title"] = "Lista de Filmes";
}

<h1>Lista de Filmes</h1>

<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Sinopse</th>
            <th>Data de Lançamento</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var filme in Model)
        {
            <tr>
                <td>@filme.Titulo</td>
                <td>@filme.Sinopse</td>
                <td>@filme.Data_lancamento.ToShortDateString()</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filmes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Filme" asp-action="Index">Filmes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filme" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filme" asp-action="Cadastro">Cadastro de Filmes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjetoMVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>